name: Deploy AWS

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      action:
        description: "apply ou destroy"
        required: false
        default: "apply"

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Clean Terraform
        run: rm -rf .terraform

      - name: Terraform Init
        run: |
          terraform init -input=false \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=state/terraform.tfstate" \
            -backend-config="region=us-east-1"

      - name: Terraform Validate
        run: terraform validate

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Run Unit Tests
        run: |
          pip install -r tests/requirements.txt
          pytest tests/test_lambda.py -v
        working-directory: .

      - name: Terraform Plan
        if: ${{ github.event.inputs.action == 'apply' || github.event.inputs.action == '' }}
        run: terraform plan -var-file="envs/dev.tfvars"

      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' || github.event.inputs.action == '' }}
        run: terraform apply -auto-approve -var-file="envs/dev.tfvars"

      - name: Run Infra Tests
        if: ${{ github.event.inputs.action == 'apply' || github.event.inputs.action == '' }}
        run: |
          pip install -r tests/requirements.txt
          pytest tests/test_infra.py -v
          echo "Infraestrutura validada com sucesso"
        working-directory: .

      - name: Empty S3 bucket (fallback)
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: |
          aws s3 rm s3://projeto-processamento-arquivos --recursive || true

      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: terraform destroy -auto-approve -refresh=false -var-file="envs/dev.tfvars"